# Generated by Django 3.2.8 on 2021-10-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='limit_date',
            field=models.DateField(null=True),
        ),
    ]
